# 💾 Establish disk file persistence context instead of volatile raw RAM
spring.datasource.url=jdbc:h2:file:./data/nexstore;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 🛠️ Allow Hibernate to sync data layers smoothly
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true